### ISSUE TITLE
Magisk Module HPESuperpower.zip

### ISSUE THREAD

**Issue by pedrobrantes** [sekedus/MagiskOnGPGPCDE#1]
The download link for the module is broken, and the official repository only has an .exe file (inside a .zip).

**Comment by sekedus** [comment]
> The download link for the module is broken

The [`HPESuperpower`](https://github.com/sekedus/MagiskOnGPGPCDE/raw/refs/heads/main/module/HPESuperpower.zip) module download link worked for me.

If the link still doesn't work for you, try downloading from here: https://github.com/sekedus/MagiskOnGPGPCDE/blob/main/module/HPESuperpower.zip

ㅤ

> official repository only has an .exe file (inside a .zip)

Which method do you use?

Difference: 
- `HPESuperpower` is a magisk module, only for method 1
- `hpesuperpower` repo is intended for root, only for method 2
